name: sync-branch-github-action
description: Sync branch with GitHub Actions.
author: remarkablemark

inputs:
  base:
    description: Base branch
    required: true
  head:
    description: Head branch (e.g., master)
    default: ${{ github.event.repository.default_branch }}
  merge:
    description: Merge method (merge, squash, rebase, admin)
    default: merge
  title:
    description: Pull request title
  body:
    description: Pull request body
  delete-branch:
    description: Delete the local and remote branch after merge
  token:
    description: GitHub token
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get pull request inputs
      id: inputs
      shell: bash
      run: |
        PULL_REQUEST_TITLE=${{ toJSON(inputs.title) }}
        if [ "$PULL_REQUEST_TITLE" == '' ]; then
          PULL_REQUEST_TITLE=$(cat <<EOF
        chore(sync-branch): merge ${{ inputs.head }} to ${{ inputs.base }}
        EOF
        )
        fi
        echo "PULL_REQUEST_TITLE=$PULL_REQUEST_TITLE" >> $GITHUB_OUTPUT

        PULL_REQUEST_BODY=${{ toJSON(inputs.body) }}
        if [ "$PULL_REQUEST_BODY" == '' ]; then
          PULL_REQUEST_BODY=$(cat <<EOF
        🤖 [sync-branch](https://github.com/remarkablemark/sync-branch): merging __${{ inputs.head }}__ to __${{ inputs.base }}__
        EOF
        )
        fi
        echo "PULL_REQUEST_BODY=$PULL_REQUEST_BODY" >> $GITHUB_OUTPUT

    - name: Create pull request
      id: pull_request
      continue-on-error: true
      shell: bash
      run: |
        PULL_REQUEST_URL=$(
          gh pr create \
            --base ${{ inputs.base }} \
            --head ${{ inputs.head }} \
            --title ${{ toJSON(steps.inputs.outputs.PULL_REQUEST_TITLE) }} \
            --body ${{ toJSON(steps.inputs.outputs.PULL_REQUEST_BODY) }}
        )
        echo "PULL_REQUEST_URL=$PULL_REQUEST_URL" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Merge pull request
      if: ${{ steps.pull_request.outputs.PULL_REQUEST_URL }}
      shell: bash
      run: >
        gh pr merge ${{ steps.pull_request.outputs.PULL_REQUEST_URL }}
        ${{ format('--{0}', inputs.merge) }}
        ${{ inputs.merge != 'admin' && '--auto' }}
        ${{ inputs.delete-branch == 'true' && '--delete-branch' }}
      env:
        GH_TOKEN: ${{ inputs.token }}

branding:
  icon: git-merge
  color: purple
